<a href="https://colab.research.google.com/github/MorningStarTM/word-ordering-/blob/main/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import random
import re

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

              Ordered
0        I love dogs.
1   She plays tennis.
2  They drink coffee.
3      He eats pizza.
4     We go shopping.

In [25]:
def unordered_text(data):
  unordered_list = []
  for i in range(len(data)):
    text = data['Ordered'][i].replace(".","")
    splited = text.split()
    random.shuffle(splited)
    un_text = ' '.join(splited)
    unordered_list.append(un_text)
  return unordered_list

In [28]:
temp = unordered_text(df)

In [30]:
df['Unordered'] = temp

In [33]:
df.head(10)

                  Ordered              Unordered
0            I love dogs.            I dogs love
1       She plays tennis.       She plays tennis
2      They drink coffee.      drink They coffee
3          He eats pizza.          He eats pizza
4         We go shopping.         We go shopping
5  She dances gracefully.  She gracefully dances
6           He runs fast.           runs fast He
7        They swim daily.        They daily swim
8           I study hard.           hard I study
9  She sings beautifully.  sings beautifully She